
package View;

public class AddAdmTeDisplay extends javax.swing.JFrame {

    public AddAdmTeDisplay() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_BG = new javax.swing.JPanel();
        jPanel_Header = new javax.swing.JPanel();
        jLabel_Title = new javax.swing.JLabel();
        jButton_Confirm = new javax.swing.JButton();
        jButton_Back = new javax.swing.JButton();
        jLabel_Info = new javax.swing.JLabel();
        jLabel_Info4 = new javax.swing.JLabel();
        jLabel_Info6 = new javax.swing.JLabel();
        jLabel_Info5 = new javax.swing.JLabel();
        jLabel_Info3 = new javax.swing.JLabel();
        jLabel_Info2 = new javax.swing.JLabel();
        jTextField_Name = new javax.swing.JTextField();
        jTextField_Mail = new javax.swing.JTextField();
        jTextField_Ced = new javax.swing.JTextField();
        jTextField_Birth = new javax.swing.JTextField();
        jTextField_Dir = new javax.swing.JTextField();
        jTextField_Sex = new javax.swing.JTextField();
        jLabel_Info1 = new javax.swing.JLabel();
        jLabel_Info7 = new javax.swing.JLabel();
        jTextField_PhoneHome = new javax.swing.JTextField();
        jTextField_PhoneCel = new javax.swing.JTextField();
        jLabel_Info8 = new javax.swing.JLabel();
        jTextField_PhoneOther = new javax.swing.JTextField();
        jLabel_Info9 = new javax.swing.JLabel();
        jTextField_User = new javax.swing.JTextField();
        jLabel_Info10 = new javax.swing.JLabel();
        jTextField_Pass = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_BG.setBackground(new java.awt.Color(255, 255, 255));

        jPanel_Header.setBackground(new java.awt.Color(0, 51, 204));

        jLabel_Title.setFont(new java.awt.Font("Gill Sans MT", 1, 42)); // NOI18N
        jLabel_Title.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Title.setText("CREAR ADMIN DE TEATRO");

        javax.swing.GroupLayout jPanel_HeaderLayout = new javax.swing.GroupLayout(jPanel_Header);
        jPanel_Header.setLayout(jPanel_HeaderLayout);
        jPanel_HeaderLayout.setHorizontalGroup(
            jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_HeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_HeaderLayout.setVerticalGroup(
            jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_HeaderLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jButton_Confirm.setBackground(new java.awt.Color(0, 51, 204));
        jButton_Confirm.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jButton_Confirm.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Confirm.setText("CONFIRMAR");
        jButton_Confirm.setToolTipText("");

        jButton_Back.setBackground(new java.awt.Color(0, 51, 204));
        jButton_Back.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jButton_Back.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Back.setText("REGRESAR");

        jLabel_Info.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Info.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Info.setText("NOMBRE:");

        jLabel_Info4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Info4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Info4.setText("DIRECCION");
        jLabel_Info4.setToolTipText("");

        jLabel_Info6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Info6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Info6.setText("CORREO:");

        jLabel_Info5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Info5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Info5.setText("SEXO (M/F)");

        jLabel_Info3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Info3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Info3.setText("NACIMIENTO (YYYY-MM-DD)");

        jLabel_Info2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Info2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Info2.setText("CEDULA:");

        jTextField_Name.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jTextField_Mail.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jTextField_Ced.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jTextField_Birth.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jTextField_Dir.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jTextField_Sex.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel_Info1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Info1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Info1.setText("TELEFONO CEL:");

        jLabel_Info7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Info7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Info7.setText("TELEFONO CASA:");

        jTextField_PhoneHome.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jTextField_PhoneCel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel_Info8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Info8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Info8.setText("TELEFONO OTRO:");

        jTextField_PhoneOther.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel_Info9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Info9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Info9.setText("USUARIO:");
        jLabel_Info9.setToolTipText("");

        jTextField_User.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel_Info10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Info10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Info10.setText("CONTRASENA:");

        jTextField_Pass.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel_BGLayout = new javax.swing.GroupLayout(jPanel_BG);
        jPanel_BG.setLayout(jPanel_BGLayout);
        jPanel_BGLayout.setHorizontalGroup(
            jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_BGLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Confirm)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_BGLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_Info3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Info2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Info4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Info5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Info6, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Ced, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Birth, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Dir, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Mail, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Sex, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_Info8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Info7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Info1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Info9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Info10, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_PhoneCel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_PhoneHome, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_PhoneOther, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_User, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        jPanel_BGLayout.setVerticalGroup(
            jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BGLayout.createSequentialGroup()
                .addComponent(jPanel_Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_Confirm, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jButton_Back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_BGLayout.createSequentialGroup()
                        .addGroup(jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Info, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Info2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Ced, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Info3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Birth, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Info4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Dir, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)))
                    .addGroup(jPanel_BGLayout.createSequentialGroup()
                        .addGroup(jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Info1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_PhoneCel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Info7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_PhoneHome, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Info8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_PhoneOther, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_User, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Info9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Info5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Sex, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jLabel_Info10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Pass, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Info6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Mail, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_Back;
    public javax.swing.JButton jButton_Confirm;
    private javax.swing.JLabel jLabel_Info;
    private javax.swing.JLabel jLabel_Info1;
    private javax.swing.JLabel jLabel_Info10;
    private javax.swing.JLabel jLabel_Info2;
    private javax.swing.JLabel jLabel_Info3;
    private javax.swing.JLabel jLabel_Info4;
    private javax.swing.JLabel jLabel_Info5;
    private javax.swing.JLabel jLabel_Info6;
    private javax.swing.JLabel jLabel_Info7;
    private javax.swing.JLabel jLabel_Info8;
    private javax.swing.JLabel jLabel_Info9;
    private javax.swing.JLabel jLabel_Title;
    private javax.swing.JPanel jPanel_BG;
    private javax.swing.JPanel jPanel_Header;
    public javax.swing.JTextField jTextField_Birth;
    public javax.swing.JTextField jTextField_Ced;
    public javax.swing.JTextField jTextField_Dir;
    public javax.swing.JTextField jTextField_Mail;
    public javax.swing.JTextField jTextField_Name;
    public javax.swing.JTextField jTextField_Pass;
    public javax.swing.JTextField jTextField_PhoneCel;
    public javax.swing.JTextField jTextField_PhoneHome;
    public javax.swing.JTextField jTextField_PhoneOther;
    public javax.swing.JTextField jTextField_Sex;
    public javax.swing.JTextField jTextField_User;
    // End of variables declaration//GEN-END:variables
}
