
package View;

public class AdmTeMenuDisplay extends javax.swing.JFrame {

    public AdmTeMenuDisplay() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_BG = new javax.swing.JPanel();
        jPanel_Header = new javax.swing.JPanel();
        jLabel_Title = new javax.swing.JLabel();
        jButton_NewProd = new javax.swing.JButton();
        jButton_UpdProd = new javax.swing.JButton();
        jButton_NewAgent = new javax.swing.JButton();
        jButton_NewPres = new javax.swing.JButton();
        jButton_NewPrice = new javax.swing.JButton();
        jButton_Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_BG.setBackground(new java.awt.Color(255, 255, 255));

        jPanel_Header.setBackground(new java.awt.Color(0, 51, 204));

        jLabel_Title.setFont(new java.awt.Font("Gill Sans MT", 1, 42)); // NOI18N
        jLabel_Title.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Title.setText("MENU ADMIN TEATRO");

        javax.swing.GroupLayout jPanel_HeaderLayout = new javax.swing.GroupLayout(jPanel_Header);
        jPanel_Header.setLayout(jPanel_HeaderLayout);
        jPanel_HeaderLayout.setHorizontalGroup(
            jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_HeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_HeaderLayout.setVerticalGroup(
            jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_HeaderLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jButton_NewProd.setBackground(new java.awt.Color(0, 51, 204));
        jButton_NewProd.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jButton_NewProd.setForeground(new java.awt.Color(255, 255, 255));
        jButton_NewProd.setText("AGREGAR PRODUCCION");
        jButton_NewProd.setPreferredSize(new java.awt.Dimension(124, 31));
        jButton_NewProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NewProdActionPerformed(evt);
            }
        });

        jButton_UpdProd.setBackground(new java.awt.Color(0, 51, 204));
        jButton_UpdProd.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jButton_UpdProd.setForeground(new java.awt.Color(255, 255, 255));
        jButton_UpdProd.setText("ACTUALIZAR PRODUCCION");
        jButton_UpdProd.setPreferredSize(new java.awt.Dimension(124, 31));

        jButton_NewAgent.setBackground(new java.awt.Color(0, 51, 204));
        jButton_NewAgent.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jButton_NewAgent.setForeground(new java.awt.Color(255, 255, 255));
        jButton_NewAgent.setText("AGREGAR AGENTE");

        jButton_NewPres.setBackground(new java.awt.Color(0, 51, 204));
        jButton_NewPres.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jButton_NewPres.setForeground(new java.awt.Color(255, 255, 255));
        jButton_NewPres.setText("AGREGAR PRESENTACION");
        jButton_NewPres.setPreferredSize(new java.awt.Dimension(124, 31));

        jButton_NewPrice.setBackground(new java.awt.Color(0, 51, 204));
        jButton_NewPrice.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jButton_NewPrice.setForeground(new java.awt.Color(255, 255, 255));
        jButton_NewPrice.setText("AGREGAR PRECIO X BLOQUE");

        jButton_Back.setBackground(new java.awt.Color(0, 51, 204));
        jButton_Back.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jButton_Back.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Back.setText("REGRESAR");

        javax.swing.GroupLayout jPanel_BGLayout = new javax.swing.GroupLayout(jPanel_BG);
        jPanel_BG.setLayout(jPanel_BGLayout);
        jPanel_BGLayout.setHorizontalGroup(
            jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_BGLayout.createSequentialGroup()
                .addGroup(jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_BGLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_NewPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_NewAgent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_UpdProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_NewPres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_NewProd, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_BGLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_BGLayout.setVerticalGroup(
            jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BGLayout.createSequentialGroup()
                .addComponent(jPanel_Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jButton_NewProd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_NewPres, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_UpdProd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_NewPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_NewAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_NewProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NewProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_NewProdActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_Back;
    public javax.swing.JButton jButton_NewAgent;
    public javax.swing.JButton jButton_NewPres;
    public javax.swing.JButton jButton_NewPrice;
    public javax.swing.JButton jButton_NewProd;
    public javax.swing.JButton jButton_UpdProd;
    private javax.swing.JLabel jLabel_Title;
    private javax.swing.JLabel jLabel_Title1;
    private javax.swing.JLabel jLabel_Title2;
    private javax.swing.JPanel jPanel_BG;
    private javax.swing.JPanel jPanel_BG1;
    private javax.swing.JPanel jPanel_BG2;
    private javax.swing.JPanel jPanel_Header;
    private javax.swing.JPanel jPanel_Header1;
    private javax.swing.JPanel jPanel_Header2;
    // End of variables declaration//GEN-END:variables
}
