
package View;

import javax.swing.DefaultComboBoxModel;

public class PartInformationDisplay extends javax.swing.JFrame {
    
    public DefaultComboBoxModel comboBoxModelFab;
    public DefaultComboBoxModel comboBoxModelBrand;

    public PartInformationDisplay() {
        initComponents();
        this.comboBoxModelFab = (DefaultComboBoxModel) jComboBox_Fab.getModel();
        this.comboBoxModelBrand = (DefaultComboBoxModel) jComboBox_Brand.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_BG = new javax.swing.JPanel();
        jPanel_Header = new javax.swing.JPanel();
        jLabel_Title = new javax.swing.JLabel();
        jLabel_Name = new javax.swing.JLabel();
        jLabel_Fab = new javax.swing.JLabel();
        jLabel_Brand = new javax.swing.JLabel();
        jButton_Accept = new javax.swing.JButton();
        jTextField_Name = new javax.swing.JTextField();
        jComboBox_Fab = new javax.swing.JComboBox<>();
        jComboBox_Brand = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_BG.setBackground(new java.awt.Color(255, 255, 255));

        jPanel_Header.setBackground(new java.awt.Color(153, 0, 0));

        jLabel_Title.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel_Title.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Title.setText("INFORMACION DE PARTE");

        javax.swing.GroupLayout jPanel_HeaderLayout = new javax.swing.GroupLayout(jPanel_Header);
        jPanel_Header.setLayout(jPanel_HeaderLayout);
        jPanel_HeaderLayout.setHorizontalGroup(
            jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_HeaderLayout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(jLabel_Title)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel_HeaderLayout.setVerticalGroup(
            jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_HeaderLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel_Title)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jLabel_Name.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel_Name.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Name.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_Name.setText("NOMBRE:");

        jLabel_Fab.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel_Fab.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Fab.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_Fab.setText("FABRICANTE:");

        jLabel_Brand.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel_Brand.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Brand.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_Brand.setText("MARCA:");

        jButton_Accept.setBackground(new java.awt.Color(153, 0, 0));
        jButton_Accept.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jButton_Accept.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Accept.setText("ACEPTAR");

        jTextField_Name.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N

        jComboBox_Fab.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jComboBox_Fab.setForeground(new java.awt.Color(0, 0, 0));

        jComboBox_Brand.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jComboBox_Brand.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel_BGLayout = new javax.swing.GroupLayout(jPanel_BG);
        jPanel_BG.setLayout(jPanel_BGLayout);
        jPanel_BGLayout.setHorizontalGroup(
            jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_BGLayout.createSequentialGroup()
                .addGroup(jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_BGLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_Fab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Brand, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField_Name)
                            .addComponent(jComboBox_Fab, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox_Brand, javax.swing.GroupLayout.Alignment.LEADING, 0, 345, Short.MAX_VALUE)))
                    .addGroup(jPanel_BGLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jButton_Accept, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_BGLayout.setVerticalGroup(
            jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BGLayout.createSequentialGroup()
                .addComponent(jPanel_Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Name)
                    .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Fab)
                    .addComponent(jComboBox_Fab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Brand)
                    .addComponent(jComboBox_Brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jButton_Accept, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_Accept;
    public javax.swing.JComboBox<String> jComboBox_Brand;
    public javax.swing.JComboBox<String> jComboBox_Fab;
    private javax.swing.JLabel jLabel_Brand;
    private javax.swing.JLabel jLabel_Fab;
    private javax.swing.JLabel jLabel_Name;
    private javax.swing.JLabel jLabel_Title;
    private javax.swing.JPanel jPanel_BG;
    private javax.swing.JPanel jPanel_Header;
    public javax.swing.JTextField jTextField_Name;
    // End of variables declaration//GEN-END:variables
}
