
package View;

public class PurchasePreviewDisplay extends javax.swing.JFrame {

    public PurchasePreviewDisplay() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_BG = new javax.swing.JPanel();
        jPanel_Header = new javax.swing.JPanel();
        jLabel_Title = new javax.swing.JLabel();
        jButton_PayCard = new javax.swing.JButton();
        jButton_Back = new javax.swing.JButton();
        jLabel_Info = new javax.swing.JLabel();
        jLabel_Info4 = new javax.swing.JLabel();
        jLabel_Info6 = new javax.swing.JLabel();
        jLabel_Info5 = new javax.swing.JLabel();
        jLabel_Info3 = new javax.swing.JLabel();
        jLabel_Info2 = new javax.swing.JLabel();
        jLabel_Cost = new javax.swing.JLabel();
        jLabel_Seats = new javax.swing.JLabel();
        jLabel_Block = new javax.swing.JLabel();
        jLabel_Time = new javax.swing.JLabel();
        jLabel_Show = new javax.swing.JLabel();
        jLabel_Theater = new javax.swing.JLabel();
        jButton_PayCash = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_BG.setBackground(new java.awt.Color(255, 255, 255));

        jPanel_Header.setBackground(new java.awt.Color(0, 51, 204));

        jLabel_Title.setFont(new java.awt.Font("Gill Sans MT", 1, 42)); // NOI18N
        jLabel_Title.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Title.setText("RESUMEN DE COMPRA");

        javax.swing.GroupLayout jPanel_HeaderLayout = new javax.swing.GroupLayout(jPanel_Header);
        jPanel_Header.setLayout(jPanel_HeaderLayout);
        jPanel_HeaderLayout.setHorizontalGroup(
            jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_HeaderLayout.createSequentialGroup()
                .addContainerGap(312, Short.MAX_VALUE)
                .addComponent(jLabel_Title)
                .addContainerGap(288, Short.MAX_VALUE))
        );
        jPanel_HeaderLayout.setVerticalGroup(
            jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_HeaderLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jButton_PayCard.setBackground(new java.awt.Color(0, 51, 204));
        jButton_PayCard.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jButton_PayCard.setForeground(new java.awt.Color(255, 255, 255));
        jButton_PayCard.setText("PAGO TARJETA");
        jButton_PayCard.setToolTipText("");

        jButton_Back.setBackground(new java.awt.Color(0, 51, 204));
        jButton_Back.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jButton_Back.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Back.setText("REGRESAR");

        jLabel_Info.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Info.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Info.setText("TEATRO:");

        jLabel_Info4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Info4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Info4.setText("BLOQUE:");
        jLabel_Info4.setToolTipText("");

        jLabel_Info6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Info6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Info6.setText("COSTO:");

        jLabel_Info5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Info5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Info5.setText("ASIENTOS:");

        jLabel_Info3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Info3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Info3.setText("FECHA/HORA:");

        jLabel_Info2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Info2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Info2.setText("OBRA:");

        jLabel_Cost.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Cost.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel_Seats.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Seats.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel_Block.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Block.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_Block.setToolTipText("");

        jLabel_Time.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Time.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel_Show.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Show.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_Show.setToolTipText("");

        jLabel_Theater.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Theater.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButton_PayCash.setBackground(new java.awt.Color(0, 51, 204));
        jButton_PayCash.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jButton_PayCash.setForeground(new java.awt.Color(255, 255, 255));
        jButton_PayCash.setText("PAGO EFECTIVO");
        jButton_PayCash.setToolTipText("");

        javax.swing.GroupLayout jPanel_BGLayout = new javax.swing.GroupLayout(jPanel_BG);
        jPanel_BG.setLayout(jPanel_BGLayout);
        jPanel_BGLayout.setHorizontalGroup(
            jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_BGLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_BGLayout.createSequentialGroup()
                        .addComponent(jButton_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_PayCash)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_PayCard))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_BGLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_Info3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Info2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Info4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Info5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Info6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel_Seats, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Block, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Time, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Show, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Theater, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Cost, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_BGLayout.setVerticalGroup(
            jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BGLayout.createSequentialGroup()
                .addComponent(jPanel_Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_PayCard, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_PayCash, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton_Back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(jPanel_BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_BGLayout.createSequentialGroup()
                        .addComponent(jLabel_Info, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_Info2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_Info3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_Info4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_Info5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_Info6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_BGLayout.createSequentialGroup()
                        .addComponent(jLabel_Theater, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jLabel_Show, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_Block, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_Seats, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_Cost, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(86, 86, 86))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_Back;
    public javax.swing.JButton jButton_PayCard;
    public javax.swing.JButton jButton_PayCash;
    public javax.swing.JLabel jLabel_Block;
    public javax.swing.JLabel jLabel_Cost;
    private javax.swing.JLabel jLabel_Info;
    private javax.swing.JLabel jLabel_Info2;
    private javax.swing.JLabel jLabel_Info3;
    private javax.swing.JLabel jLabel_Info4;
    private javax.swing.JLabel jLabel_Info5;
    private javax.swing.JLabel jLabel_Info6;
    public javax.swing.JLabel jLabel_Seats;
    public javax.swing.JLabel jLabel_Show;
    public javax.swing.JLabel jLabel_Theater;
    public javax.swing.JLabel jLabel_Time;
    private javax.swing.JLabel jLabel_Title;
    private javax.swing.JPanel jPanel_BG;
    private javax.swing.JPanel jPanel_Header;
    // End of variables declaration//GEN-END:variables
}
